# Generated by Django 4.1.3 on 2022-11-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=512)),
                ('moneyAvailability', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('spendingLimit', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
