# Generated by Django 4.1.3 on 2022-11-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='moneyAvailability',
            new_name='availability',
        ),
    ]
