# Generated by Django 4.1.3 on 2022-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_moneyavailability_user_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spendingLimit',
            field=models.DecimalField(db_column='spending', decimal_places=2, max_digits=10000),
        ),
    ]
