# Generated by Django 4.1.3 on 2022-11-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_spendinglimit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='spendingLimit',
            new_name='spendable',
        ),
    ]
