# Generated by Django 4.1.3 on 2022-12-08 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
