# Generated by Django 4.1.3 on 2022-12-12 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=512, validators=[django.core.validators.MinLengthValidator(8)])),
                ('availability', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('spendable', models.DecimalField(db_column='spending', decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
