# Generated by Django 4.1.3 on 2022-12-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_manage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manage',
        ),
    ]
