# Generated by Django 4.1.3 on 2022-12-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_delete_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='author',
            field=models.CharField(default='', max_length=256),
        ),
    ]
