# Generated by Django 4.1.3 on 2022-12-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='username',
            new_name='name',
        ),
    ]
