# Generated by Django 4.1.3 on 2022-12-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_username_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
    ]
